{
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs-18_x", "npm-9_x"]
    },
    "install": {
      "cmds": [
        "npm ci --include=dev"
      ]
    },
    "build": {
      "cmds": [
        "npx prisma generate",
        "npm run build"
      ]
    }
  },
  "start": {
    "cmd": "npm run start"
  }
}
